version: '2.1'

services:
    web:
        build: .
        command: nodemon /opt/app/ --watch
        ports:
           - "3000:3000"
        volumes:
            - .:/opt/app
        depends_on:
          db:
            condition: service_healthy
        environment:
            DATABASE_HOST: db
    db:
        image: postgres
        healthcheck:
            test: "pg_isready -h localhost -p 5432 -q -U postgres"
            interval: 3s
            timeout: 5s
            retries: 5
        restart: always
        environment:
            POSTGRES_USER: realtale
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: realtale
        ports:
            - 5432:5432
